[display]
title = "Sandbox"
demo_url = "https://sandbox.staging2.boatbumpers.io/"
overview_weight = 30

[meta]
engine = "JavaScript"
languages = ["TypeScript"]
platforms = ["HTML5"]
networking = "SocketIo"
rendering = "HTML5DOM"
features = ["Matchmaker", "DynamicServers"]

