[display]
title = "Colyseus"
description = """
This repository provides examples of running Colyseus with the Rivet plugin.

[**Live demo**](https://colyseus.rivet.game/)
""""

[meta]
engine = "JavaScript"
languages = ["TypeScript"]
networking = "Colyseus"
platforms = ["HTML5"]
features = ["Matchmaker", "DynamicServers"]
