[display]
title = "Tanks"
tutorial_url = "https://rivet.gg/learn/html5/tutorials/tanks-canvas-socketio"
overview_weight = 90

[meta]
engine = "JavaScript"
languages = ["TypeScript"]
platforms = ["HTML5"]
networking = "SocketIo"
rendering = "HTML5Canvas"
features = ["Matchmaker", "DynamicServers"]


