[display]
title = "Bomber"
tutorial_url = "https://rivet.gg/learn/godot/tutorials/crash-course"
overview_weight = 100

[meta]
engine = "Godot"
engine_version = "4.0.0"
languages = ["GDScript"]
features = ["Matchmaker", "DynamicServers"]
platforms = ["Desktop"]
networking = "GodotHLMultiplayer"


