[display]
title = "Bomber"
tutorial_url = "https://rivet.gg/learn/godot/tutorials/crash-course"
preview_file = "preview.png"
overview_weight = 100

[meta]
engine = "Godot"
engine_version = "4.0.0"
language = "GDScript"
networking = "GodotHLMultiplayer"
features = ["Matchmaker", "DynamicServers"]


