[display]
title = "Tanks"
tutorial_url = "https://rivet.gg/learn/html5/tutorials/tanks-canvas-socketio"

[meta]
engine = "HTML5"
language = "TypeScript"
networking = "SocketIo"
rendering = "HTML5Canvas"
features = ["Matchmaker", "DynamicServers"]


