[display]
title = "WebRTC"
description = """
Demonstrates low latency UDP workload using a direct `RTCDataChannel` between the client and the server.

Leverages the [`wrtc`](https://www.npmjs.com/package/wrtc) NodeJS library to run WebRTC on the server.
""""
extra_steps = [
    "npm install -g node-pre-gyp"
]

[meta]
engine = "JavaScript"
languages = ["TypeScript"]
networking = "WebRTC"
platforms = ["HTML5"]
features = ["Matchmaker", "DynamicServers"]
