[display]
title = "Tanks"
tutorial_url = "https://rivet.gg/learn/unity/tutorials/fishnet/crash-course"
preview_file = "preview.png"
overview_weight = 95

[meta]
engine = "Unity"
engine_version = "2020.3.0"
language = "CSharp"
networking = "FishNet"
features = ["Matchmaker", "DynamicServers"]


