[display]
title = "Tanks"
tutorial_url = "https://rivet.gg/learn/unity/tutorials/fishnet/crash-course"
overview_weight = 95

[meta]
engine = "Unity"
engine_version = "2022.3.18f1"
languages = ["CSharp"]
networking = "FishNet"
platforms = ["Desktop"]
features = ["Matchmaker", "DynamicServers"]


