# === Rivet Configuration ===
# 
# - More info: https://rivet.gg/docs/general/concepts/version-config
# - Reference: https://rivet.gg/docs/cloud/api/games/versions/create-game-version
# - Publish a new version with `rivet publish`
#
[engine.unity]
# How the game lobbies run and how players connect to the game.
#
# https://rivet.gg/docs/matchmaker
[matchmaker]
	# How many players can join a specific lobby.
	#
	# Read more about matchmaking: https://rivet.gg/docs/matchmaker/concepts/finding-lobby
	max_players = 32

	# The hardware to provide for lobbies.
	#
	# Available tiers: https://rivet.gg/docs/serverless-lobbies/concepts/available-tiers
	tier = "basic-1d1"

# What game modes are avaiable.
#
# Properties like `max_players`, `tier`, `dockerfile`, `regions`, and more can
# be overriden for specific game modes.
[matchmaker.game_modes]
	mode-a = {}
	mode-b = {}

	[matchmaker.game_modes.custom]
		idle_lobbies = { min = 0, max = 0 }

		[matchmaker.game_modes.custom.create_config]
			identity_requirement = "none"

			# Public custom lobbies will be listed in the response to `lobbies.list`, private custom
			# lobbies will not
			enable_public = true
			enable_private = true

# Which regions the game should be available in.
#
# Available regions: https://rivet.gg/docs/serverless-lobbies/concepts/available-regions
[matchmaker.regions]
	lnd-atl = {}
	lnd-fra = {}

# Runtime configuration for the lobby's Docker container.
[matchmaker.docker]
	# If you're unfamiliar with Docker, here's how to write your own
	# Dockerfile:
	# https://docker-curriculum.com/#dockerfile
	dockerfile = "Dockerfile"

	# Which ports to allow players to connect to. Multiple ports can be defined
	# with different protocols.
	#
	# How ports work: https://rivet.gg/docs/serverless-lobbies/concepts/ports
	ports.default = { port = 7770, protocol = "udp" }
	
# # How Rivet CDN should host your static assets on our CDN.
# #
# # https://rivet.gg/docs/cdn
# [cdn]
# 	# Command to run before uploading the site to Rivet. This can be used to
# 	# build any JavaScript bundles or generate assets.
# 	build_command = "echo 'Nothing to do'"

# 	# The folder to upload to Rivet.
# 	#
# 	# If you're hosting a website, ensure that `index.html` is in the root of
# 	# this folder.
# 	build_output = "dist/"

